import React, { useState } from 'react';
import { Layout } from '../components/layout/Layout';
import { Card } from '../components/common/Card';
import { Badge } from '../components/common/Badge';
import { Modal } from '../components/common/Modal';
import { useThreatData } from '../store/ThreatStore';
import type { Report } from '../types';
import {
  FileText,
  Download,
  Eye,
  Bot,
  CheckCircle2,
} from 'lucide-react';

export const Reports: React.FC = () => {
  const { reports: mockReports } = useThreatData();
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportNotification, setExportNotification] = useState('');

  const handleExportPDF = (reportId: string) => {
    setIsExporting(true);
    setExportNotification(`Preparing ${reportId} for PDF export...`);
    setTimeout(() => {
      setIsExporting(false);
      setExportNotification('Print dialog opened — choose Save as PDF.');
      window.print();
      setTimeout(() => setExportNotification(''), 3000);
    }, 300);
  };

  return (
    <Layout>
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-2 border-b border-slate-800/80">
        <div>
          <h1 className="text-2xl font-bold text-slate-100 tracking-tight">Investigation Reports</h1>
          <p className="text-xs text-slate-400 mt-1">
            Structured BLUF executive summaries generated by IBM Bob AI for commanders and SOC leaders
          </p>
        </div>

        {exportNotification && (
          <div className="px-4 py-2 rounded-xl bg-emerald-950 border border-emerald-800 text-emerald-300 text-xs font-semibold flex items-center space-x-2 animate-pulse">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>{exportNotification}</span>
          </div>
        )}
      </div>

      {/* Main Reports Table */}
      <Card title="Generated BLUF Reports" subtitle="Exportable PDF summaries featuring full telemetry evidence">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400 font-mono uppercase tracking-wider">
                <th className="py-3 px-4">Report ID</th>
                <th className="py-3 px-4">Correlated Incident</th>
                <th className="py-3 px-4">Priority</th>
                <th className="py-3 px-4">AI Confidence</th>
                <th className="py-3 px-4">Generated By</th>
                <th className="py-3 px-4">Created Timestamp</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {mockReports.map((report) => (
                <tr key={report.id} className="hover:bg-slate-800/60 transition-colors">
                  <td className="py-3.5 px-4 font-mono font-bold text-cyan-400">{report.id}</td>
                  <td className="py-3.5 px-4">
                    <p className="font-semibold text-slate-100">{report.incidentTitle}</p>
                    <p className="text-[11px] font-mono text-purple-400 mt-0.5">{report.incidentId}</p>
                  </td>
                  <td className="py-3.5 px-4">
                    <Badge value={report.priority} size="sm" />
                  </td>
                  <td className="py-3.5 px-4 font-mono font-bold text-slate-200">{report.confidence}%</td>
                  <td className="py-3.5 px-4 font-medium text-slate-300 flex items-center space-x-1.5 mt-1">
                    <Bot className="w-3.5 h-3.5 text-cyan-400" />
                    <span>{report.generatedBy}</span>
                  </td>
                  <td className="py-3.5 px-4 font-mono text-slate-400 whitespace-nowrap">
                    {report.created}
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <div className="flex items-center justify-end space-x-2">
                      <button
                        onClick={() => setSelectedReport(report)}
                        className="px-2.5 py-1 rounded bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-200 text-[11px] font-semibold flex items-center space-x-1 transition-colors"
                      >
                        <Eye className="w-3.5 h-3.5 text-cyan-400" />
                        <span>View</span>
                      </button>

                      <button
                        onClick={() => handleExportPDF(report.id)}
                        disabled={isExporting}
                        className="px-2.5 py-1 rounded bg-cyan-950 hover:bg-cyan-900 border border-cyan-800 text-cyan-300 text-[11px] font-semibold flex items-center space-x-1 transition-colors"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>Export PDF</span>
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Full BLUF Report Viewer Modal */}
      <Modal
        isOpen={!!selectedReport}
        onClose={() => setSelectedReport(null)}
        size="2xl"
        title={
          selectedReport ? (
            <div className="flex items-center justify-between w-full pr-6">
              <div className="flex items-center space-x-3">
                <FileText className="w-5 h-5 text-cyan-400" />
                <span className="font-bold text-slate-100">{selectedReport.id}</span>
                <Badge value={selectedReport.priority} />
              </div>
            </div>
          ) : (
            'Executive Report'
          )
        }
      >
        {selectedReport && (
          <div className="space-y-6 text-xs text-slate-200">
            {/* Header Document Info */}
            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 flex justify-between items-center">
              <div>
                <h3 className="text-base font-bold text-slate-100">{selectedReport.incidentTitle}</h3>
                <p className="text-slate-400 text-xs mt-0.5">
                  Incident: <strong className="text-purple-400">{selectedReport.incidentId}</strong> | Author:{' '}
                  {selectedReport.generatedBy}
                </p>
              </div>

              <button
                onClick={() => handleExportPDF(selectedReport.id)}
                className="px-4 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-bold text-xs flex items-center space-x-1.5 transition-all"
              >
                <Download className="w-4 h-4" />
                <span>Export PDF</span>
              </button>
            </div>

            {/* BLUF Highlight Box */}
            <div className="p-5 rounded-2xl bg-gradient-to-br from-slate-950 via-slate-950 to-cyan-950/60 border border-cyan-800/80 soc-glow-cyan">
              <span className="px-2.5 py-1 rounded bg-cyan-500 text-slate-950 font-extrabold text-xs uppercase font-mono tracking-wider">
                Bottom Line Up Front (BLUF)
              </span>
              <p className="text-sm text-slate-100 font-medium leading-relaxed mt-3 bg-slate-950/90 p-4 rounded-xl border border-slate-800">
                {selectedReport.bluf}
              </p>
            </div>

            {/* Threat Assessment & Rationale */}
            <div>
              <h4 className="font-bold text-slate-300 uppercase tracking-wider text-xs mb-2">
                Threat Assessment
              </h4>
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-slate-300 leading-relaxed">
                {selectedReport.threatAssessment}
              </div>
            </div>

            {/* Evidence List */}
            <div>
              <h4 className="font-bold text-slate-300 uppercase tracking-wider text-xs mb-2">
                Correlated Telemetry Evidence
              </h4>
              <ul className="space-y-2">
                {selectedReport.evidence.map((ev, i) => (
                  <li
                    key={i}
                    className="p-3 rounded-lg bg-slate-950 border border-slate-800 font-mono text-[11px] text-emerald-300 flex items-center gap-2"
                  >
                    <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>{ev}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Recommended Actions */}
            <div>
              <h4 className="font-bold text-emerald-400 uppercase tracking-wider text-xs mb-2">
                Commander Recommended Actions
              </h4>
              <div className="space-y-2">
                {selectedReport.recommendedActions.map((act, i) => (
                  <div
                    key={i}
                    className="p-3 rounded-lg bg-emerald-950/40 border border-emerald-900/60 text-xs font-semibold text-emerald-200"
                  >
                    {act}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </Modal>
    </Layout>
  );
};
